driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: "test/environments"
  data_bags_path: "test/data_bags"
  encrypted_data_bag_secret_key_path: "test/data_bags/wazuh_secrets/test_data_bag_key"
  product_version: latest
  cookbook_path: whatever/path/to/cookbooks

verifiers:
  name: inspec

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: centos-8.0
  - name: centos-7

suites:
  - name: opendistro
    run_list:
      - recipe['wazuh_manager::default']
      #- recipe[opendistro::default]
    driver:
      network:
        - ["private_network", {ip: "172.16.10.11"}]
      customize:
        memory: 2048
        cpus: 2


#driver:
#  name: vagrant
#  driver_config:
#   require_chef_omnibus: latest
#
#provisioner:
#  name: chef_zero
#  environments_path: "../../environments"
#  data_bags_path: "../../data_bags"
#  encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
#
#
#platforms:
#  - name: ubuntu-12.04
#    run_list: apt::default
#  - name: ubuntu-14.04
#    run_list: apt::default
#
#suites:
#  - name: default
#    driver:
#      network:
#      - ["private_network", {ip: "172.16.10.10"}]
#    run_list:
#      - recipe[wazuh_elastic::default]
#    attributes:
#