---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_version: latest

verifiers:
  name: inspec

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: centos-8.0
  - name: centos-7

suites:
  - name: filebeat
    driver:
      network:
        - ["private_network", {ip: "172.17.10.10"}]
      customize:
        memory: 512
        cpus: 1
    run_list:
      - recipe[filebeat::default]