driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: "test/environments"
  data_bags_path: "test/data_bags"
  encrypted_data_bag_secret_key_path: "test/data_bags/wazuh_secrets/test_data_bag_key"
  product_version: latest

verifiers:
  name: inspec

platforms:
  - name: ubuntu-20.04
    driver:
      network:
        - ["private_network", {ip: "172.16.11.10"}]
  - name: ubuntu-18.04
    driver:
      network:
        - ["private_network", {ip: "172.16.11.11"}]
  - name: centos-8.0
    driver:
      network:
        - ["private_network", {ip: "172.16.11.12"}]
  - name: centos-7
    driver:
      network:
        - ["private_network", {ip: "172.16.11.13"}]

suites:
  - name: elastic-stack
    run_list:
      - recipe[elastic-stack::default]
    driver:
      customize:
        memory: 4096
        cpus: 2