driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: "test/environments"
  data_bags_path: "test/data_bags"
  encrypted_data_bag_secret_key_path: "test/data_bags/wazuh_secrets/test_data_bag_key"
  product_version: latest

verifiers:
  name: inspec

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: centos-8.0
  - name: centos-7

suites:
  - name: elastic-stack
    run_list:
      - recipe[elastic-stack::default]
    driver:
      network:
        - ["private_network", {ip: "172.16.10.11"}]
      customize:
        memory: 2048
        cpus: 2