name: Kitchen tests for Wazuh Chef

on:
  push:
    branches: 
      - feature-cookbooks
  pull_request:
    branches:
      - feature-cookbooks

jobs:
  filebeat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          # amazonlinux-2,
          # debian-9,
          # debian-10,
          # centos-7,
          # centos-8,
          ubuntu-2004,
          # ubuntu-1804,
          # opensuse-leap-15,
          # fedora-latest,
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Kitchen Test
      uses: actionshub/test-kitchen@main
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.yml
      with:
        suite: filebeat
        os: ${{ matrix.os }}
        action: test
    
    #- name: Test filebeat cookbook
    #  uses: ./.github/actions
    #  env:
    #    COOKBOOK_NAME: filebeat
    #    OS: ${{ matrix.os }}
    #- name: Print out logs if fail
    #  if: ${{ failure() }}
    #  working-directory: ./.github/actions
    #  run: |
    #    chmod 755 failure.sh
    #    ./failure.sh
    #  env:
    #    COOKBOOK_NAME: filebeat
    #    OS: ${{ matrix.os }}
  
 
 