name: Kitchen tests for Wazuh Chef

on:
  push:
    branches: 
      - feature-cookbooks
  pull_request:
    branches:
      - feature-cookbooks

jobs:
  kitchen-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          # amazonlinux-2,
          # debian-9,
          # debian-10,
          # centos-7,
          # centos-8,
          ubuntu-2004,
          # ubuntu-1804,
          # opensuse-leap-15,
          # fedora-latest
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    #- name: Setup Ruby
    #  uses: actions/setup-ruby@v1
    #  with:
    #    ruby-version: '2.7'
    #- name: Install Chef
    #  uses: actionshub/chef-install@main
    #  with:
    #    version: latest
    - name: Test filebeat cookbook
      uses: ./.github/actions
      env:
        COOKBOOK_NAME: filebeat
        OS: ${{ matrix.os }}
    #- name: Print out logs if fail
    #  if: ${{ failure() }}
    #  working-directory: ./.github/actions
    #  run: |
    #    chmod 755 failure.sh
    #    ./failure.sh
    #  env:
    #    COOKBOOK_NAME: elastic-stack
    #    OS: ${{ matrix.os }}
  
 
 