name: Kitchen tests for Wazuh Chef

on:
  push:
    branches: 
      - feature-cookbooks
  pull_request:
    branches:
      - feature-cookbooks

jobs:
  ruby:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
  
  chef:
    needs: ruby
    runs-on: ubuntu-latest 
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Chef
        uses: actionshub/chef-install@main

  elastic-stack:
    needs: [ruby, chef]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          # amazonlinux-2,
          # debian-9,
          # debian-10,
          # centos-7,
          # centos-8,
          ubuntu-20.04,
          # ubuntu-18.04,
          # opensuse-leap-15,
        ]
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Elastic-Stack
        uses: ./.github/actions
        env:
          COOKBOOK_NAME: elastic-stack
          OS: ${{ matrix.os }}
  
  #opendistro:
  #  needs: [ruby, chef]
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      os: [
  #        # debian-9,
  #        # debian-10,
  #        # centos-7,
  #        # centos-8,
  #        ubuntu-20.04,
  #        # ubuntu-18.04,
  #        # opensuse-leap-15,
  #        # fedora-latest
  #      ]
  #  steps:
  #    - name: Check out code
  #      uses: actions/checkout@master
  #    - name: Opendistro
  #      uses: ./.github/actions
  #      env:
  #        COOKBOOK_NAME: opendistro
  #        OS: ${{ matrix.os }}
  #
  #filebeat:
  #  needs: [ruby, chef]
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      os: [
  #        # debian-9,
  #        # debian-10,
  #        # centos-7,
  #        # centos-8,
  #        ubuntu-20.04,
  #        # ubuntu-18.04,
  #        # opensuse-leap-15,
  #        # fedora-latest
  #      ]
  #  steps:
  #    - name: Check out code
  #      uses: actions/checkout@master
  #    - name: Filebeat
  #      uses: ./.github/actions
  #      env:
  #        COOKBOOK_NAME: filebeat
  #        OS: ${{ matrix.os }}
  #
  #
  #filebeat-oss:
  #  needs: [ruby, chef]
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      os: [
  #        # debian-9,
  #        # debian-10,
  #        # centos-7,
  #        # centos-8,
  #        ubuntu-20.04,
  #        # ubuntu-18.04,
  #        # opensuse-leap-15,
  #        # fedora-latest
  #      ]
  #  steps:
  #    - name: Check out code
  #      uses: actions/checkout@master
  #    - name: Filebeat-OSS
  #      uses: ./.github/actions
  #      env:
  #        COOKBOOK_NAME: filebeat-oss
  #        OS: ${{ matrix.os }}
  #
  #wazuh-manager:
  #  needs: [ruby, chef]
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      os: [
  #        # debian-9,
  #        # debian-10,
  #        # centos-7,
  #        # centos-8,
  #        ubuntu-20.04,
  #        # ubuntu-18.04,
  #        # opensuse-leap-15,
  #        # fedora-latest
  #      ]
  #  steps:
  #    - name: Check out code
  #      uses: actions/checkout@master
  #    - name: Wazuh Manager
  #      uses: ./.github/actions
  #      env:
  #        COOKBOOK_NAME: wazuh_manager
  #        OS: ${{ matrix.os }}
  #
  #wazuh-agent:
  #  needs: [ruby, chef]
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      os: [
  #        # debian-9,
  #        # debian-10,
  #        # centos-7,
  #        # centos-8,
  #        ubuntu-20.04,
  #        # ubuntu-18.04,
  #        # opensuse-leap-15,
  #        # fedora-latest
  #      ]
  #  steps:
  #    - name: Check out code
  #      uses: actions/checkout@master
  #    - name: Wazuh Agent 
  #      uses: ./.github/actions
  #      env:
  #        COOKBOOK_NAME: wazuh_agent
  #        OS: ${{ matrix.os }}
 