name: Kitchen tests for Wazuh Chef

on:
  push:
    branches: 
      - feature-cookbooks
  pull_request:
    branches:
      - feature-cookbooks

jobs:
  wazuh-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          centos-8,
          ubuntu-2004,
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Wazuh server (manager, filebeat)
      uses: actionshub/kitchen-dokken@main
      env:
        suite: wazuh-server
        os: ${{ matrix.os }}
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml

  wazuh-server-oss:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          centos-8,
          ubuntu-2004,
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Wazuh server OSS (manager, filebeat-oss)
      uses: actionshub/kitchen-dokken@main
      env:
        suite: wazuh-server-oss
        os: ${{ matrix.os }}
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml

  opendistro:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          centos-8,
          ubuntu-2004,
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Opendistro
      uses: actionshub/kitchen-dokken@main
      env:
        suite: opendistro
        os: ${{ matrix.os }}
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
  
  elastic-stack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          centos-8,
          ubuntu-2004,
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Elastic Stack 
      uses: actionshub/kitchen-dokken@main
      env:
        suite: elastic-stack
        os: ${{ matrix.os }}
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml

  wazuh-agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [
          centos-8,
          ubuntu-2004,
        ]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Wazuh agent
      uses: actionshub/kitchen-dokken@main
      env:
        suite: wazuh-agent
        os: ${{ matrix.os }}
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml