name: Kitchen tests for Wazuh Chef

on:
  push:
    branches: 
      - feature-cookbooks
  pull_request:
    branches:
      - feature-cookbooks

jobs:
  kitchen-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Chef
        uses: actionshub/chef-install@master
      - name: Dokken
        uses: actionshub/kitchen-dokken@creation
        env:
          suite: default
          os: ubuntu-1804
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
      #- name: Ubuntu 18.04 - Wazuh Manager
      #  uses: ./.github/actions/manager
      #  env:
      #    IMAGE: jrei/systemd-ubuntu:18.04
      #    PLATFORM: ubuntu
      #    RELEASE: 18
      #    RUN_COMMAND: /sbin/init
      #    VAGRANT_INSTANCE: wazuh-manager-ubuntu-1804

 