name: Kitchen tests for Wazuh Chef

on:
  push:
    branches: 
      - feature-cookbooks
  pull_request:
    branches:
      - feature-cookbooks

jobs:
  kitchen-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          #- 'debian-9'
          #- 'debian-10'
          #- 'centos-7'
          #- 'centos-8'
          #- 'ubuntu-1604'
          - 'ubuntu-1804'
          #- 'opensuse-leap-15'
        suite:
          - 'default'
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Chef
        uses: actionshub/chef-install@master
      - name: Ubuntu 18.04 - Wazuh Manager
        uses: ./.github/actions/manager
        env:
          IMAGE: jrei/systemd-ubuntu:18.04
          PLATFORM: ubuntu
          RELEASE: 18
          RUN_COMMAND: /sbin/init
          VAGRANT_INSTANCE: wazuh-manager-ubuntu-1804

 