name: Kitchen tests for Wazuh Chef

on:
  push:
    branches: 
      - feature-cookbooks
  pull_request:
    branches:
      - feature-cookbooks

jobs:
  kitchen-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['debian-8', 'debian-9', 'centos-7', 'fedora-latest', 'ubuntu-1604', 'ubuntu-1804']
        suite: ['default']
      fail-fast: false
    steps:
    #- name: Check out code
    #  uses: actions/checkout@v2
    #- name: Set up Ruby
    #  uses: ruby/setup-ruby@v1
    #  with:
    #    ruby-version: 2.6
    #- name: Ubuntu 18.04 - Wazuh Manager
    #  uses: ./.github/actions/manager
    #  env:
    #    IMAGE: jrei/systemd-ubuntu:18.04
    #    PLATFORM: ubuntu
    #    RELEASE: 18
    #    RUN_COMMAND: /sbin/init
    #    VAGRANT_INSTANCE: wazuh-manager-ubuntu-1804
    - name: Check out code
      uses: actions/checkout@main
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Test-Kitchen
      uses: actionshub/test-kitchen@main
      with:
        suite: ${{ matrix.suite }}
        os: ${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml