name: Ruby

on:
  push:
    branches: 
      - feature-cookbooks
  pull_request:
    branches:
      - feature-cookbooks

jobs:
  ubuntu18:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Ubuntu 18.04 - Wazuh Manager
      uses: ./.github/actions/manager
      env:
        IMAGE: jrei/systemd-ubuntu:18.04
        PLATFORM: ubuntu
        RELEASE: 18
        RUN_COMMAND: /sbin/init
        VAGRANT_INSTANCE: wazuh-manager-ubuntu-1804