name: Kitchen tests for Wazuh Chef

on:
  push:
    branches: 
      - feature-cookbooks
  pull_request:
    branches:
      - feature-cookbooks

jobs:
  wazuh-manager:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Test ${{ matrix.suite }} cookbook
      uses: actionshub/test-kitchen@main
      env:
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.yml
      with:
        suite: wazuh-manager
        os: centos-8
        action: converge
  wazuh-agent:
    runs-on: ubuntu-latest
    needs: wazuh-manager    