name: Ruby

on:
  push:
    branches: 
      - feature-cookbooks
  pull_request:
    branches:
      - feature-cookbooks

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Install Chef Workstation
      uses: actionshub/chef-install@main